insert into product(name, category, price, manufacturer, unitInStock, description) values ("LG 그램", "컴퓨터", 180, "LG전자", 100, "2020 최신형")
insert into product(name, category, price, manufacturer, unitInStock, description) values ("삼성 Always", "컴퓨터", 180, "삼성전자", 100, "2020 최신형")
insert into product(name, category, price, manufacturer, unitInStock, description) values ("맥북 노트북", "컴퓨터", 270, "애플", 80, "2020 최신형")
insert into product(name, category, price, manufacturer, unitInStock, description) values ("TV", "가전", 500, "LG전자", 20, "OLED")
insert into product(name, category, price, manufacturer, unitInStock, description) values ("에어맥스 운동화", "잡화", 15, "나이키", 65, "폭신폭신 에어맥스")
insert into product(name, category, price, manufacturer, unitInStock, description) values ("러닝화", "잡화", 10, "뉴발란스", 70, "편안한 착용감")
insert into product(name, category, price, manufacturer, unitInStock, description) values ("컨버스 운동화", "잡화", 5, "컨버스", 100, "컨버스 하이")
insert into product(name, category, price, manufacturer, unitInStock, description) values ("갤럭시 노트", "컴퓨터", 100, "삼성전자", 100, "스마트폰")
insert into product(name, category, price, manufacturer, unitInStock, description) values ("V50", "컴퓨터", 110, "LG전자", 100, "스마트폰")
insert into product(name, category, price, manufacturer, unitInStock, description) values ("아이폰", "컴퓨터", 119, "애플", 100, "스마트폰")